from models import Movie
import csv

class MovieRepository:
    """ The repository for the movie model """

    def post_all_db():

        
        Movie(key=13, title= '''Balto''', director='', date=1995, genre='''Adventure''').save()
        Movie(key=14, title= '''Nixon''', director='', date=1995, genre='''Drama''').save()
        Movie(key=15, title= '''Cutthroat Island''', director='', date=1995, genre='''Action''').save()
        Movie(key=16, title= '''Casino''', director='', date=1995, genre='''Crime''').save()
        Movie(key=17, title= '''Sense and Sensibility''', director='', date=1995, genre='''Drama''').save()
        Movie(key=18, title= '''Four Rooms''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=19, title= '''Ace Ventura: When Nature Calls''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=20, title= '''Money Train''', director='', date=1995, genre='''Action''').save()
        Movie(key=21, title= '''Get Shorty''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=22, title= '''Copycat''', director='', date=1995, genre='''Crime''').save()
        Movie(key=23, title= '''Assassins''', director='', date=1995, genre='''Action''').save()
        Movie(key=24, title= '''Powder''', director='', date=1995, genre='''Drama''').save()
        Movie(key=25, title= '''Leaving Las Vegas''', director='', date=1995, genre='''Drama''').save()
        Movie(key=26, title= '''Othello''', director='', date=1995, genre='''Drama''').save()
        Movie(key=27, title= '''Now and Then''', director='', date=1995, genre='''Children''').save()
        Movie(key=28, title= '''Persuasion''', director='', date=1995, genre='''Drama''').save()
        Movie(key=29, title= '''"City of Lost Children, The (Cité des enfants perdus, La)''', director='', date=1995, genre='''Adventure''').save()
        Movie(key=30, title= '''Shanghai Triad (Yao a yao yao dao waipo qiao)''', director='', date=1995, genre='''Crime''').save()
        Movie(key=31, title= '''Dangerous Minds''', director='', date=1995, genre='''Drama''').save()
        Movie(key=32, title= '''Twelve Monkeys (a.k.a. 12 Monkeys)''', director='', date=1995, genre='''Mystery''').save()
        Movie(key=34, title= '''Babe''', director='', date=1995, genre='''Children''').save()
        Movie(key=36, title= '''Dead Man Walking''', director='', date=1995, genre='''Crime''').save()
        Movie(key=38, title= '''It Takes Two''', director='', date=1995, genre='''Children''').save()
        Movie(key=39, title= '''Clueless''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=40, title= '''"Cry the Beloved Country''', director='', date=1995, genre='''Drama''').save()
        Movie(key=41, title= '''Richard III''', director='', date=1995, genre='''Drama''').save()
        Movie(key=42, title= '''Dead Presidents''', director='', date=1995, genre='''Action''').save()
        Movie(key=43, title= '''Restoration''', director='', date=1995, genre='''Drama''').save()
        Movie(key=44, title= '''Mortal Kombat''', director='', date=1995, genre='''Action''').save()
        Movie(key=45, title= '''To Die For''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=46, title= '''How to Make an American Quilt''', director='', date=1995, genre='''Drama''').save()
        Movie(key=47, title= '''Seven (a.k.a. Se7en)''', director='', date=1995, genre='''Mystery''').save()
        Movie(key=48, title= '''Pocahontas''', director='', date=1995, genre='''Animation''').save()
        Movie(key=49, title= '''When Night Is Falling''', director='', date=1995, genre='''Drama''').save()
        Movie(key=50, title= '''"Usual Suspects, The''', director='', date=1995, genre='''Crime''').save()
        Movie(key=52, title= '''Mighty Aphrodite''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=53, title= '''Lamerica''', director='', date=1994, genre='''Adventure''').save()
        Movie(key=54, title= '''"Big Green, The''', director='', date=1995, genre='''Children''').save()
        Movie(key=55, title= '''Georgia''', director='', date=1995, genre='''Drama''').save()
        Movie(key=57, title= '''Home for the Holidays''', director='', date=1995, genre='''Drama''').save()
        Movie(key=58, title= '''"Postman The (Postino, Il)''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=60, title= '''"Indian in the Cupboard, The''', director='', date=1995, genre='''Adventure''').save()
        Movie(key=61, title= '''Eye for an Eye''', director='', date=1996, genre='''Drama''').save()
        Movie(key=62, title= '''Mr. Holland's Opus''', director='', date=1995, genre='''Drama''').save()
        Movie(key=63, title= '''Don't Be a Menace to South Central While Drinking Your Juice in the Hood''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=64, title= '''Two if by Sea''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=65, title= '''Bio-Dome''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=66, title= '''Lawnmower Man 2: Beyond Cyberspace''', director='', date=1996, genre='''Action''').save()
        Movie(key=68, title= '''French Twist (Gazon maudit)''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=69, title= '''Friday''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=70, title= '''From Dusk Till Dawn''', director='', date=1996, genre='''Action''').save()
        Movie(key=71, title= '''Fair Game''', director='', date=1995, genre='''Action''').save()
        Movie(key=72, title= '''Kicking and Screaming''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=73, title= '''"Misérables Les''', director='', date=1995, genre='''Drama''').save()
        Movie(key=74, title= '''Bed of Roses''', director='', date=1996, genre='''Drama''').save()
        Movie(key=75, title= '''Big Bully''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=76, title= '''Screamers''', director='', date=1995, genre='''Action''').save()
        Movie(key=77, title= '''Nico Icon''', director='', date=1995, genre='''Documentary''').save()
        Movie(key=78, title= '''"Crossing Guard, The''', director='', date=1995, genre='''Action''').save()
        Movie(key=79, title= '''"Juror The''', director='', date=1996, genre='''Drama''').save()
        Movie(key=80, title= '''"White Balloon, The (Badkonake sefid)''', director='', date=1995, genre='''Children''').save()
        Movie(key=81, title= '''Things to Do in Denver When You're Dead''', director='', date=1995, genre='''Crime''').save()
        Movie(key=82, title= '''Antonia's Line (Antonia)''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=83, title= '''Once Upon a Time... When We Were Colored''', director='', date=1995, genre='''Drama''').save()
        Movie(key=85, title= '''Angels and Insects''', director='', date=1995, genre='''Drama''').save()
        Movie(key=86, title= '''White Squall''', director='', date=1996, genre='''Action''').save()
        Movie(key=87, title= '''Dunston Checks In''', director='', date=1996, genre='''Children''').save()
        Movie(key=88, title= '''Black Sheep''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=89, title= '''Nick of Time''', director='', date=1995, genre='''Action''').save()
        Movie(key=92, title= '''Mary Reilly''', director='', date=1996, genre='''Drama''').save()
        Movie(key=93, title= '''Vampire in Brooklyn''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=94, title= '''Beautiful Girls''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=95, title= '''Broken Arrow''', director='', date=1996, genre='''Action''').save()
        Movie(key=96, title= '''In the Bleak Midwinter''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=97, title= '''"Hate (Haine, La)''', director='', date=1995, genre='''Crime''').save()
        Movie(key=99, title= '''Heidi Fleiss: Hollywood Madam''', director='', date=1995, genre='''Documentary''').save()
        Movie(key=100, title= '''City Hall''', director='', date=1996, genre='''Drama''').save()
        Movie(key=101, title= '''Bottle Rocket''', director='', date=1996, genre='''Adventure''').save()
        Movie(key=102, title= '''Mr. Wrong''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=103, title= '''Unforgettable''', director='', date=1996, genre='''Mystery''').save()
        Movie(key=104, title= '''Happy Gilmore''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=105, title= '''"Bridges of Madison County, The''', director='', date=1995, genre='''Drama''').save()
        Movie(key=106, title= '''Nobody Loves Me (Keiner liebt mich)''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=107, title= '''Muppet Treasure Island''', director='', date=1996, genre='''Adventure''').save()
        Movie(key=108, title= '''Catwalk''', director='', date=1996, genre='''Documentary''').save()
        Movie(key=110, title= '''Braveheart''', director='', date=1995, genre='''Action''').save()
        Movie(key=111, title= '''Taxi Driver''', director='', date=1976, genre='''Crime''').save()
        Movie(key=112, title= '''Rumble in the Bronx (Hont faan kui)''', director='', date=1995, genre='''Action''').save()
        Movie(key=113, title= '''Before and After''', director='', date=1996, genre='''Drama''').save()
        Movie(key=116, title= '''Anne Frank Remembered''', director='', date=1995, genre='''Documentary''').save()
        Movie(key=117, title= '''"Young Poisoner's Handbook, The''', director='', date=1995, genre='''Crime''').save()
        Movie(key=118, title= '''If Lucy Fell''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=119, title= '''"Steal Big, Steal Little''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=121, title= '''"Boys of St. Vincent, The''', director='', date=1992, genre='''Drama''').save()
        Movie(key=122, title= '''Boomerang''', director='', date=1992, genre='''Comedy''').save()
        Movie(key=123, title= '''Chungking Express (Chung Hing sam lam)''', director='', date=1994, genre='''Drama''').save()
        Movie(key=125, title= '''Flirting With Disaster''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=126, title= '''"NeverEnding Story III, The''', director='', date=1994, genre='''Adventure''').save()
        Movie(key=128, title= '''Jupiter's Wife''', director='', date=1994, genre='''Documentary''').save()
        Movie(key=129, title= '''Pie in the Sky''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=132, title= '''Jade''', director='', date=1995, genre='''Thriller''').save()
        Movie(key=135, title= '''Down Periscope''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=137, title= '''Man of the Year''', director='', date=1995, genre='''Documentary''').save()
        Movie(key=140, title= '''Up Close and Personal''', director='', date=1996, genre='''Drama''').save()
        Movie(key=141, title= '''"Birdcage The''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=144, title= '''"Brothers McMullen, The''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=145, title= '''Bad Boys''', director='', date=1995, genre='''Action''').save()
        Movie(key=146, title= '''"Amazing Panda Adventure, The''', director='', date=1995, genre='''Adventure''').save()
        Movie(key=147, title= '''"Basketball Diaries, The''', director='', date=1995, genre='''Drama''').save()
        Movie(key=148, title= '''"Awfully Big Adventure, An''', director='', date=1995, genre='''Drama''').save()
        Movie(key=149, title= '''Amateur''', director='', date=1994, genre='''Crime''').save()
        Movie(key=150, title= '''Apollo 13''', director='', date=1995, genre='''Adventure''').save()
        Movie(key=151, title= '''Rob Roy''', director='', date=1995, genre='''Action''').save()
        Movie(key=152, title= '''"Addiction The''', director='', date=1995, genre='''Drama''').save()
        Movie(key=153, title= '''Batman Forever''', director='', date=1995, genre='''Action''').save()
        Movie(key=154, title= '''Beauty of the Day (Belle de jour)''', director='', date=1967, genre='''Drama''').save()
        Movie(key=155, title= '''Beyond Rangoon''', director='', date=1995, genre='''Adventure''').save()
        Movie(key=156, title= '''Blue in the Face''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=157, title= '''Canadian Bacon''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=158, title= '''Casper''', director='', date=1995, genre='''Adventure''').save()
        Movie(key=159, title= '''Clockers''', director='', date=1995, genre='''Crime''').save()
        Movie(key=160, title= '''Congo''', director='', date=1995, genre='''Action''').save()
        Movie(key=161, title= '''Crimson Tide''', director='', date=1995, genre='''Drama''').save()
        Movie(key=162, title= '''Crumb''', director='', date=1994, genre='''Documentary''').save()
        Movie(key=163, title= '''Desperado''', director='', date=1995, genre='''Action''').save()
        Movie(key=164, title= '''Devil in a Blue Dress''', director='', date=1995, genre='''Crime''').save()
        Movie(key=165, title= '''Die Hard: With a Vengeance''', director='', date=1995, genre='''Action''').save()
        Movie(key=166, title= '''"Doom Generation, The''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=168, title= '''First Knight''', director='', date=1995, genre='''Action''').save()
        Movie(key=169, title= '''Free Willy 2: The Adventure Home''', director='', date=1995, genre='''Adventure''').save()
        Movie(key=170, title= '''Hackers''', director='', date=1995, genre='''Action''').save()
        Movie(key=171, title= '''Jeffrey''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=172, title= '''Johnny Mnemonic''', director='', date=1995, genre='''Action''').save()
        Movie(key=173, title= '''Judge Dredd''', director='', date=1995, genre='''Action''').save()
        Movie(key=174, title= '''Jury Duty''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=175, title= '''Kids''', director='', date=1995, genre='''Drama''').save()
        Movie(key=176, title= '''Living in Oblivion''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=177, title= '''Lord of Illusions''', director='', date=1995, genre='''Horror''').save()
        Movie(key=178, title= '''Love & Human Remains''', director='', date=1993, genre='''Comedy''').save()
        Movie(key=179, title= '''Mad Love''', director='', date=1995, genre='''Drama''').save()
        Movie(key=180, title= '''Mallrats''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=181, title= '''Mighty Morphin Power Rangers: The Movie''', director='', date=1995, genre='''Action''').save()
        Movie(key=183, title= '''Mute Witness''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=184, title= '''Nadja''', director='', date=1994, genre='''Drama''').save()
        Movie(key=185, title= '''"Net The''', director='', date=1995, genre='''Action''').save()
        Movie(key=186, title= '''Nine Months''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=187, title= '''Party Girl''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=188, title= '''"Prophecy The''', director='', date=1995, genre='''Fantasy''').save()
        Movie(key=189, title= '''Reckless''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=190, title= '''Safe''', director='', date=1995, genre='''Thriller''').save()
        Movie(key=191, title= '''"Scarlet Letter, The''', director='', date=1995, genre='''Drama''').save()
        Movie(key=193, title= '''Showgirls''', director='', date=1995, genre='''Drama''').save()
        Movie(key=194, title= '''Smoke''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=195, title= '''Something to Talk About''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=196, title= '''Species''', director='', date=1995, genre='''Horror''').save()
        Movie(key=198, title= '''Strange Days''', director='', date=1995, genre='''Action''').save()
        Movie(key=199, title= '''"Umbrellas of Cherbourg, The (Parapluies de Cherbourg, Les)''', director='', date=1964, genre='''Drama''').save()
        Movie(key=201, title= '''Three Wishes''', director='', date=1995, genre='''Drama''').save()
        Movie(key=202, title= '''Total Eclipse''', director='', date=1995, genre='''Drama''').save()
        Movie(key=203, title= '''"To Wong Foo, Thanks for Everything! Julie Newmar''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=204, title= '''Under Siege 2: Dark Territory''', director='', date=1995, genre='''Action''').save()
        Movie(key=205, title= '''Unstrung Heroes''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=206, title= '''Unzipped''', director='', date=1995, genre='''Documentary''').save()
        Movie(key=207, title= '''"Walk in the Clouds, A''', director='', date=1995, genre='''Drama''').save()
        Movie(key=208, title= '''Waterworld''', director='', date=1995, genre='''Action''').save()
        Movie(key=209, title= '''White Man's Burden''', director='', date=1995, genre='''Drama''').save()
        Movie(key=210, title= '''Wild Bill''', director='', date=1995, genre='''Western''').save()
        Movie(key=211, title= '''"Browning Version, The''', director='', date=1994, genre='''Drama''').save()
        Movie(key=212, title= '''Bushwhacked''', director='', date=1995, genre='''Adventure''').save()
        Movie(key=213, title= '''Burnt by the Sun (Utomlyonnye solntsem)''', director='', date=1994, genre='''Drama''').save()
        Movie(key=214, title= '''Before the Rain (Pred dozhdot)''', director='', date=1994, genre='''Drama''').save()
        Movie(key=215, title= '''Before Sunrise''', director='', date=1995, genre='''Drama''').save()
        Movie(key=216, title= '''Billy Madison''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=217, title= '''"Babysitter The''', director='', date=1995, genre='''Drama''').save()
        Movie(key=218, title= '''Boys on the Side''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=219, title= '''"Cure The''', director='', date=1995, genre='''Drama''').save()
        Movie(key=220, title= '''Castle Freak''', director='', date=1995, genre='''Horror''').save()
        Movie(key=222, title= '''Circle of Friends''', director='', date=1995, genre='''Drama''').save()
        Movie(key=223, title= '''Clerks''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=224, title= '''Don Juan DeMarco''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=225, title= '''Disclosure''', director='', date=1994, genre='''Drama''').save()
        Movie(key=227, title= '''Drop Zone''', director='', date=1994, genre='''Action''').save()
        Movie(key=228, title= '''Destiny Turns on the Radio''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=229, title= '''Death and the Maiden''', director='', date=1994, genre='''Drama''').save()
        Movie(key=230, title= '''Dolores Claiborne''', director='', date=1995, genre='''Drama''').save()
        Movie(key=231, title= '''Dumb & Dumber (Dumb and Dumber)''', director='', date=1994, genre='''Adventure''').save()
        Movie(key=232, title= '''Eat Drink Man Woman (Yin shi nan nu)''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=233, title= '''Exotica''', director='', date=1994, genre='''Drama''').save()
        Movie(key=234, title= '''Exit to Eden''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=235, title= '''Ed Wood''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=236, title= '''French Kiss''', director='', date=1995, genre='''Action''').save()
        Movie(key=237, title= '''Forget Paris''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=238, title= '''Far From Home: The Adventures of Yellow Dog''', director='', date=1995, genre='''Adventure''').save()
        Movie(key=239, title= '''"Goofy Movie, A''', director='', date=1995, genre='''Animation''').save()
        Movie(key=240, title= '''Hideaway''', director='', date=1995, genre='''Thriller''').save()
        Movie(key=241, title= '''Fluke''', director='', date=1995, genre='''Children''').save()
        Movie(key=242, title= '''Farinelli: il castrato''', director='', date=1994, genre='''Drama''').save()
        Movie(key=243, title= '''Gordy''', director='', date=1995, genre='''Children''').save()
        Movie(key=246, title= '''Hoop Dreams''', director='', date=1994, genre='''Documentary''').save()
        Movie(key=247, title= '''Heavenly Creatures''', director='', date=1994, genre='''Crime''').save()
        Movie(key=248, title= '''Houseguest''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=249, title= '''Immortal Beloved''', director='', date=1994, genre='''Drama''').save()
        Movie(key=250, title= '''Heavyweights (Heavy Weights)''', director='', date=1995, genre='''Children''').save()
        Movie(key=251, title= '''"Hunted The''', director='', date=1995, genre='''Action''').save()
        Movie(key=252, title= '''I.Q.''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=253, title= '''Interview with the Vampire: The Vampire Chronicles''', director='', date=1994, genre='''Drama''').save()
        Movie(key=254, title= '''Jefferson in Paris''', director='', date=1995, genre='''Drama''').save()
        Movie(key=255, title= '''"Jerky Boys, The''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=256, title= '''Junior''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=257, title= '''Just Cause''', director='', date=1995, genre='''Mystery''').save()
        Movie(key=258, title= '''"Kid in King Arthur's Court, A''', director='', date=1995, genre='''Adventure''').save()
        Movie(key=259, title= '''Kiss of Death''', director='', date=1995, genre='''Crime''').save()
        Movie(key=260, title= '''Star Wars: Episode IV - A New Hope''', director='', date=1977, genre='''Action''').save()
        Movie(key=261, title= '''Little Women''', director='', date=1994, genre='''Drama''').save()
        Movie(key=262, title= '''"Little Princess, A''', director='', date=1995, genre='''Children''').save()
        Movie(key=263, title= '''Ladybird Ladybird''', director='', date=1994, genre='''Drama''').save()
        Movie(key=265, title= '''Like Water for Chocolate (Como agua para chocolate)''', director='', date=1992, genre='''Drama''').save()
        Movie(key=266, title= '''Legends of the Fall''', director='', date=1994, genre='''Drama''').save()
        Movie(key=267, title= '''Major Payne''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=269, title= '''My Crazy Life (Mi vida loca)''', director='', date=1993, genre='''Drama''').save()
        Movie(key=270, title= '''Love Affair''', director='', date=1994, genre='''Drama''').save()
        Movie(key=271, title= '''Losing Isaiah''', director='', date=1995, genre='''Drama''').save()
        Movie(key=272, title= '''"Madness of King George, The''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=273, title= '''Mary Shelley's Frankenstein (Frankenstein)''', director='', date=1994, genre='''Drama''').save()
        Movie(key=274, title= '''Man of the House''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=275, title= '''Mixed Nuts''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=276, title= '''Milk Money''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=277, title= '''Miracle on 34th Street''', director='', date=1994, genre='''Drama''').save()
        Movie(key=278, title= '''Miami Rhapsody''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=279, title= '''My Family''', director='', date=1995, genre='''Drama''').save()
        Movie(key=280, title= '''Murder in the First''', director='', date=1995, genre='''Drama''').save()
        Movie(key=281, title= '''Nobody's Fool''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=282, title= '''Nell''', director='', date=1994, genre='''Drama''').save()
        Movie(key=283, title= '''New Jersey Drive''', director='', date=1995, genre='''Crime''').save()
        Movie(key=284, title= '''New York Cop (Nyû Yôku no koppu)''', director='', date=1993, genre='''Action''').save()
        Movie(key=285, title= '''Beyond Bedlam''', director='', date=1993, genre='''Drama''').save()
        Movie(key=287, title= '''Nina Takes a Lover''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=288, title= '''Natural Born Killers''', director='', date=1994, genre='''Action''').save()
        Movie(key=289, title= '''Only You''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=290, title= '''Once Were Warriors''', director='', date=1994, genre='''Crime''').save()
        Movie(key=291, title= '''Poison Ivy II''', director='', date=1996, genre='''Drama''').save()
        Movie(key=292, title= '''Outbreak''', director='', date=1995, genre='''Action''').save()
        Movie(key=293, title= '''Léon: The Professional (a.k.a. The Professional) (Léon)''', director='', date=1994, genre='''Action''').save()
        Movie(key=294, title= '''"Perez Family, The''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=295, title= '''"Pyromaniac's Love Story, A''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=296, title= '''Pulp Fiction''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=298, title= '''Pushing Hands (Tui shou)''', director='', date=1992, genre='''Drama''').save()
        Movie(key=299, title= '''Priest''', director='', date=1994, genre='''Drama''').save()
        Movie(key=300, title= '''Quiz Show''', director='', date=1994, genre='''Drama''').save()
        Movie(key=301, title= '''Picture Bride (Bijo photo)''', director='', date=1994, genre='''Drama''').save()
        Movie(key=302, title= '''"Queen Margot (Reine Margot, La)''', director='', date=1994, genre='''Drama''').save()
        Movie(key=303, title= '''"Quick and the Dead, The''', director='', date=1995, genre='''Action''').save()
        Movie(key=304, title= '''Roommates''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=305, title= '''Ready to Wear (Pret-A-Porter)''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=306, title= '''Three Colors: Red (Trois couleurs: Rouge)''', director='', date=1994, genre='''Drama''').save()
        Movie(key=307, title= '''Three Colors: Blue (Trois couleurs: Bleu)''', director='', date=1993, genre='''Drama''').save()
        Movie(key=308, title= '''Three Colors: White (Trzy kolory: Bialy)''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=310, title= '''Rent-a-Kid''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=311, title= '''Relative Fear''', director='', date=1994, genre='''Horror''').save()
        Movie(key=312, title= '''Stuart Saves His Family''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=313, title= '''"Swan Princess, The''', director='', date=1994, genre='''Animation''').save()
        Movie(key=314, title= '''"Secret of Roan Inish, The''', director='', date=1994, genre='''Children''').save()
        Movie(key=315, title= '''"Specialist The''', director='', date=1994, genre='''Action''').save()
        Movie(key=316, title= '''Stargate''', director='', date=1994, genre='''Action''').save()
        Movie(key=317, title= '''"Santa Clause, The''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=318, title= '''"Shawshank Redemption, The''', director='', date=1994, genre='''Crime''').save()
        Movie(key=319, title= '''Shallow Grave''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=320, title= '''Suture''', director='', date=1993, genre='''Film-Noir''').save()
        Movie(key=321, title= '''Strawberry and Chocolate (Fresa y chocolate)''', director='', date=1993, genre='''Drama''').save()
        Movie(key=322, title= '''Swimming with Sharks''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=324, title= '''"Sum of Us, The''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=325, title= '''National Lampoon's Senior Trip''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=326, title= '''To Live (Huozhe)''', director='', date=1994, genre='''Drama''').save()
        Movie(key=327, title= '''Tank Girl''', director='', date=1995, genre='''Action''').save()
        Movie(key=328, title= '''Tales from the Crypt Presents: Demon Knight''', director='', date=1995, genre='''Horror''').save()
        Movie(key=329, title= '''Star Trek: Generations''', director='', date=1994, genre='''Adventure''').save()
        Movie(key=330, title= '''Tales from the Hood''', director='', date=1995, genre='''Action''').save()
        Movie(key=331, title= '''Tom & Viv''', director='', date=1994, genre='''Drama''').save()
        Movie(key=332, title= '''Village of the Damned''', director='', date=1995, genre='''Horror''').save()
        Movie(key=333, title= '''Tommy Boy''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=334, title= '''Vanya on 42nd Street''', director='', date=1994, genre='''Drama''').save()
        Movie(key=335, title= '''Underneath''', director='', date=1995, genre='''Mystery''').save()
        Movie(key=336, title= '''"Walking Dead, The''', director='', date=1995, genre='''Drama''').save()
        Movie(key=337, title= '''What's Eating Gilbert Grape''', director='', date=1993, genre='''Drama''').save()
        Movie(key=338, title= '''Virtuosity''', director='', date=1995, genre='''Action''').save()
        Movie(key=339, title= '''While You Were Sleeping''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=340, title= '''"War The''', director='', date=1994, genre='''Adventure''').save()
        Movie(key=341, title= '''Double Happiness''', director='', date=1994, genre='''Drama''').save()
        Movie(key=342, title= '''Muriel's Wedding''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=343, title= '''"Baby-Sitters Club, The''', director='', date=1995, genre='''Children''').save()
        Movie(key=344, title= '''Ace Ventura: Pet Detective''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=345, title= '''"Adventures of Priscilla, Queen of the Desert, The''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=346, title= '''Backbeat''', director='', date=1993, genre='''Drama''').save()
        Movie(key=347, title= '''Bitter Moon''', director='', date=1992, genre='''Drama''').save()
        Movie(key=348, title= '''Bullets Over Broadway''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=349, title= '''Clear and Present Danger''', director='', date=1994, genre='''Action''').save()
        Movie(key=350, title= '''"Client The''', director='', date=1994, genre='''Drama''').save()
        Movie(key=351, title= '''"Corrina Corrina''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=352, title= '''Crooklyn''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=353, title= '''"Crow The''', director='', date=1994, genre='''Action''').save()
        Movie(key=354, title= '''Cobb''', director='', date=1994, genre='''Drama''').save()
        Movie(key=355, title= '''"Flintstones The''', director='', date=1994, genre='''Children''').save()
        Movie(key=356, title= '''Forrest Gump''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=357, title= '''Four Weddings and a Funeral''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=358, title= '''Higher Learning''', director='', date=1995, genre='''Drama''').save()
        Movie(key=359, title= '''I Like It Like That''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=360, title= '''I Love Trouble''', director='', date=1994, genre='''Action''').save()
        Movie(key=361, title= '''It Could Happen to You''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=362, title= '''"Jungle Book, The''', director='', date=1994, genre='''Adventure''').save()
        Movie(key=363, title= '''"Wonderful Horrible Life of Leni Riefenstahl, The (Macht der Bilder: Leni Riefenstahl, Die)''', director='', date=1993, genre='''Documentary''').save()
        Movie(key=364, title= '''"Lion King, The''', director='', date=1994, genre='''Adventure''').save()
        Movie(key=365, title= '''Little Buddha''', director='', date=1993, genre='''Drama''').save()
        Movie(key=366, title= '''"Wes Craven's New Nightmare (Nightmare on Elm Street Part 7: Freddy's Finale, A)''', director='', date=1994, genre='''Drama''').save()
        Movie(key=367, title= '''"Mask The''', director='', date=1994, genre='''Action''').save()
        Movie(key=368, title= '''Maverick''', director='', date=1994, genre='''Adventure''').save()
        Movie(key=369, title= '''Mrs. Parker and the Vicious Circle''', director='', date=1994, genre='''Drama''').save()
        Movie(key=370, title= '''Naked Gun 33 1/3: The Final Insult''', director='', date=1994, genre='''Action''').save()
        Movie(key=371, title= '''"Paper The''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=372, title= '''Reality Bites''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=373, title= '''Red Rock West''', director='', date=1992, genre='''Thriller''').save()
        Movie(key=374, title= '''Richie Rich''', director='', date=1994, genre='''Children''').save()
        Movie(key=376, title= '''"River Wild, The''', director='', date=1994, genre='''Action''').save()
        Movie(key=377, title= '''Speed''', director='', date=1994, genre='''Action''').save()
        Movie(key=378, title= '''Speechless''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=379, title= '''Timecop''', director='', date=1994, genre='''Action''').save()
        Movie(key=380, title= '''True Lies''', director='', date=1994, genre='''Action''').save()
        Movie(key=381, title= '''When a Man Loves a Woman''', director='', date=1994, genre='''Drama''').save()
        Movie(key=382, title= '''Wolf''', director='', date=1994, genre='''Drama''').save()
        Movie(key=383, title= '''Wyatt Earp''', director='', date=1994, genre='''Western''').save()
        Movie(key=384, title= '''Bad Company''', director='', date=1995, genre='''Action''').save()
        Movie(key=385, title= '''"Man of No Importance, A''', director='', date=1994, genre='''Drama''').save()
        Movie(key=386, title= '''S.F.W.''', director='', date=1994, genre='''Drama''').save()
        Movie(key=387, title= '''"Low Down Dirty Shame, A''', director='', date=1994, genre='''Action''').save()
        Movie(key=388, title= '''Boys Life''', director='', date=1995, genre='''Drama''').save()
        Movie(key=389, title= '''"Colonel Chabert, Le''', director='', date=1994, genre='''Drama''').save()
        Movie(key=390, title= '''Faster Pussycat! Kill! Kill!''', director='', date=1965, genre='''Action''').save()
        Movie(key=391, title= '''Jason's Lyric''', director='', date=1994, genre='''Crime''').save()
        Movie(key=393, title= '''Street Fighter''', director='', date=1994, genre='''Action''').save()
        Movie(key=405, title= '''Highlander III: The Sorcerer (a.k.a. Highlander: The Final Dimension)''', director='', date=1994, genre='''Action''').save()
        Movie(key=406, title= '''Federal Hill''', director='', date=1994, genre='''Drama''').save()
        Movie(key=407, title= '''In the Mouth of Madness''', director='', date=1995, genre='''Horror''').save()
        Movie(key=408, title= '''8 Seconds''', director='', date=1994, genre='''Drama''').save()
        Movie(key=409, title= '''Above the Rim''', director='', date=1994, genre='''Crime''').save()
        Movie(key=410, title= '''Addams Family Values''', director='', date=1993, genre='''Children''').save()
        Movie(key=412, title= '''"Age of Innocence, The''', director='', date=1993, genre='''Drama''').save()
        Movie(key=413, title= '''Airheads''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=414, title= '''"Air Up There, The''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=415, title= '''Another Stakeout''', director='', date=1993, genre='''Comedy''').save()
        Movie(key=416, title= '''Bad Girls''', director='', date=1994, genre='''Western''').save()
        Movie(key=417, title= '''Barcelona''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=418, title= '''Being Human''', director='', date=1993, genre='''Drama''').save()
        Movie(key=419, title= '''"Beverly Hillbillies, The''', director='', date=1993, genre='''Comedy''').save()
        Movie(key=420, title= '''Beverly Hills Cop III''', director='', date=1994, genre='''Action''').save()
        Movie(key=421, title= '''Black Beauty''', director='', date=1994, genre='''Adventure''').save()
        Movie(key=422, title= '''Blink''', director='', date=1994, genre='''Thriller''').save()
        Movie(key=423, title= '''Blown Away''', director='', date=1994, genre='''Action''').save()
        Movie(key=424, title= '''Blue Chips''', director='', date=1994, genre='''Drama''').save()
        Movie(key=425, title= '''Blue Sky''', director='', date=1994, genre='''Drama''').save()
        Movie(key=426, title= '''Body Snatchers''', director='', date=1993, genre='''Horror''').save()
        Movie(key=427, title= '''Boxing Helena''', director='', date=1993, genre='''Drama''').save()
        Movie(key=428, title= '''"Bronx Tale, A''', director='', date=1993, genre='''Drama''').save()
        Movie(key=429, title= '''Cabin Boy''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=430, title= '''Calendar Girl''', director='', date=1993, genre='''Comedy''').save()
        Movie(key=431, title= '''Carlito's Way''', director='', date=1993, genre='''Crime''').save()
        Movie(key=432, title= '''City Slickers II: The Legend of Curly's Gold''', director='', date=1994, genre='''Adventure''').save()
        Movie(key=433, title= '''Clean Slate''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=434, title= '''Cliffhanger''', director='', date=1993, genre='''Action''').save()
        Movie(key=435, title= '''Coneheads''', director='', date=1993, genre='''Comedy''').save()
        Movie(key=436, title= '''Color of Night''', director='', date=1994, genre='''Drama''').save()
        Movie(key=437, title= '''Cops and Robbersons''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=438, title= '''"Cowboy Way, The''', director='', date=1994, genre='''Action''').save()
        Movie(key=440, title= '''Dave''', director='', date=1993, genre='''Comedy''').save()
        Movie(key=441, title= '''Dazed and Confused''', director='', date=1993, genre='''Comedy''').save()
        Movie(key=442, title= '''Demolition Man''', director='', date=1993, genre='''Action''').save()
        Movie(key=444, title= '''Even Cowgirls Get the Blues''', director='', date=1993, genre='''Comedy''').save()
        Movie(key=445, title= '''Fatal Instinct''', director='', date=1993, genre='''Comedy''').save()
        Movie(key=446, title= '''Farewell My Concubine (Ba wang bie ji)''', director='', date=1993, genre='''Drama''').save()
        Movie(key=448, title= '''Fearless''', director='', date=1993, genre='''Drama''').save()
        Movie(key=449, title= '''Fear of a Black Hat''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=450, title= '''With Honors''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=451, title= '''Flesh and Bone''', director='', date=1993, genre='''Drama''').save()
        Movie(key=452, title= '''Widows' Peak''', director='', date=1994, genre='''Drama''').save()
        Movie(key=453, title= '''For Love or Money''', director='', date=1993, genre='''Comedy''').save()
        Movie(key=454, title= '''"Firm The''', director='', date=1993, genre='''Drama''').save()
        Movie(key=455, title= '''Free Willy''', director='', date=1993, genre='''Adventure''').save()
        Movie(key=456, title= '''Fresh''', director='', date=1994, genre='''Crime''').save()
        Movie(key=457, title= '''"Fugitive The''', director='', date=1993, genre='''Thriller''').save()
        Movie(key=458, title= '''Geronimo: An American Legend''', director='', date=1993, genre='''Drama''').save()
        Movie(key=459, title= '''"Getaway The''', director='', date=1994, genre='''Action''').save()
        Movie(key=460, title= '''Getting Even with Dad''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=461, title= '''Go Fish''', director='', date=1994, genre='''Drama''').save()
        Movie(key=464, title= '''Hard Target''', director='', date=1993, genre='''Action''').save()
        Movie(key=466, title= '''Hot Shots! Part Deux''', director='', date=1993, genre='''Action''').save()
        Movie(key=467, title= '''Live Nude Girls''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=468, title= '''"Englishman Who Went Up a Hill But Came Down a Mountain, The''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=469, title= '''"House of the Spirits, The''', director='', date=1993, genre='''Drama''').save()
        Movie(key=470, title= '''House Party 3''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=471, title= '''"Hudsucker Proxy, The''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=472, title= '''I'll Do Anything''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=473, title= '''In the Army Now''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=474, title= '''In the Line of Fire''', director='', date=1993, genre='''Action''').save()
        Movie(key=475, title= '''In the Name of the Father''', director='', date=1993, genre='''Drama''').save()
        Movie(key=476, title= '''"Inkwell The''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=477, title= '''What's Love Got to Do with It?''', director='', date=1993, genre='''Drama''').save()
        Movie(key=478, title= '''Jimmy Hollywood''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=479, title= '''Judgment Night''', director='', date=1993, genre='''Action''').save()
        Movie(key=480, title= '''Jurassic Park''', director='', date=1993, genre='''Action''').save()
        Movie(key=481, title= '''Kalifornia''', director='', date=1993, genre='''Drama''').save()
        Movie(key=482, title= '''Killing Zoe''', director='', date=1994, genre='''Crime''').save()
        Movie(key=484, title= '''Lassie''', director='', date=1994, genre='''Adventure''').save()
        Movie(key=485, title= '''Last Action Hero''', director='', date=1993, genre='''Action''').save()
        Movie(key=486, title= '''Life with Mikey''', director='', date=1993, genre='''Comedy''').save()
        Movie(key=487, title= '''Lightning Jack''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=488, title= '''M. Butterfly''', director='', date=1993, genre='''Drama''').save()
        Movie(key=489, title= '''Made in America''', director='', date=1993, genre='''Comedy''').save()
        Movie(key=490, title= '''Malice''', director='', date=1993, genre='''Thriller''').save()
        Movie(key=491, title= '''"Man Without a Face, The''', director='', date=1993, genre='''Drama''').save()
        Movie(key=492, title= '''Manhattan Murder Mystery''', director='', date=1993, genre='''Comedy''').save()
        Movie(key=493, title= '''Menace II Society''', director='', date=1993, genre='''Action''').save()
        Movie(key=494, title= '''Executive Decision''', director='', date=1996, genre='''Action''').save()
        Movie(key=495, title= '''In the Realm of the Senses (Ai no corrida)''', director='', date=1976, genre='''Drama''').save()
        Movie(key=496, title= '''What Happened Was...''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=497, title= '''Much Ado About Nothing''', director='', date=1993, genre='''Comedy''').save()
        Movie(key=499, title= '''Mr. Wonderful''', director='', date=1993, genre='''Comedy''').save()
        Movie(key=500, title= '''Mrs. Doubtfire''', director='', date=1993, genre='''Comedy''').save()
        Movie(key=501, title= '''Naked''', director='', date=1993, genre='''Drama''').save()
        Movie(key=502, title= '''"Next Karate Kid, The''', director='', date=1994, genre='''Action''').save()
        Movie(key=504, title= '''No Escape''', director='', date=1994, genre='''Action''').save()
        Movie(key=505, title= '''North''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=506, title= '''Orlando''', director='', date=1992, genre='''Drama''').save()
        Movie(key=507, title= '''"Perfect World, A''', director='', date=1993, genre='''Crime''').save()
        Movie(key=508, title= '''Philadelphia''', director='', date=1993, genre='''Drama''').save()
        Movie(key=509, title= '''"Piano The''', director='', date=1993, genre='''Drama''').save()
        Movie(key=510, title= '''Poetic Justice''', director='', date=1993, genre='''Drama''').save()
        Movie(key=511, title= '''"Program The''', director='', date=1993, genre='''Action''').save()
        Movie(key=512, title= '''"Puppet Masters, The''', director='', date=1994, genre='''Horror''').save()
        Movie(key=513, title= '''Radioland Murders''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=514, title= '''"Ref The''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=515, title= '''"Remains of the Day, The''', director='', date=1993, genre='''Drama''').save()
        Movie(key=516, title= '''Renaissance Man''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=517, title= '''Rising Sun''', director='', date=1993, genre='''Action''').save()
        Movie(key=518, title= '''"Road to Wellville, The''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=519, title= '''RoboCop 3''', director='', date=1993, genre='''Action''').save()
        Movie(key=520, title= '''Robin Hood: Men in Tights''', director='', date=1993, genre='''Comedy''').save()
        Movie(key=521, title= '''Romeo Is Bleeding''', director='', date=1993, genre='''Crime''').save()
        Movie(key=522, title= '''Romper Stomper''', director='', date=1992, genre='''Action''').save()
        Movie(key=523, title= '''Ruby in Paradise''', director='', date=1993, genre='''Drama''').save()
        Movie(key=524, title= '''Rudy''', director='', date=1993, genre='''Drama''').save()
        Movie(key=526, title= '''"Savage Nights (Nuits fauves, Les)''', director='', date=1992, genre='''Drama''').save()
        Movie(key=527, title= '''Schindler's List''', director='', date=1993, genre='''Drama''').save()
        Movie(key=528, title= '''"Scout The''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=529, title= '''Searching for Bobby Fischer''', director='', date=1993, genre='''Drama''').save()
        Movie(key=531, title= '''"Secret Garden, The''', director='', date=1993, genre='''Children''').save()
        Movie(key=532, title= '''Serial Mom''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=533, title= '''"Shadow The''', director='', date=1994, genre='''Action''').save()
        Movie(key=534, title= '''Shadowlands''', director='', date=1993, genre='''Drama''').save()
        Movie(key=535, title= '''Short Cuts''', director='', date=1993, genre='''Drama''').save()
        Movie(key=536, title= '''"Simple Twist of Fate, A''', director='', date=1994, genre='''Drama''').save()
        Movie(key=537, title= '''Sirens''', director='', date=1994, genre='''Drama''').save()
        Movie(key=538, title= '''Six Degrees of Separation''', director='', date=1993, genre='''Drama''').save()
        Movie(key=539, title= '''Sleepless in Seattle''', director='', date=1993, genre='''Comedy''').save()
        Movie(key=540, title= '''Sliver''', director='', date=1993, genre='''Thriller''').save()
        Movie(key=541, title= '''Blade Runner''', director='', date=1982, genre='''Action''').save()
        Movie(key=542, title= '''Son in Law''', director='', date=1993, genre='''Comedy''').save()
        Movie(key=543, title= '''So I Married an Axe Murderer''', director='', date=1993, genre='''Comedy''').save()
        Movie(key=544, title= '''Striking Distance''', director='', date=1993, genre='''Action''').save()
        Movie(key=546, title= '''Super Mario Bros.''', director='', date=1993, genre='''Action''').save()
        Movie(key=547, title= '''Surviving the Game''', director='', date=1994, genre='''Action''').save()
        Movie(key=548, title= '''Terminal Velocity''', director='', date=1994, genre='''Action''').save()
        Movie(key=549, title= '''Thirty-Two Short Films About Glenn Gould''', director='', date=1993, genre='''Drama''').save()
        Movie(key=550, title= '''Threesome''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=551, title= '''"Nightmare Before Christmas, The''', director='', date=1993, genre='''Animation''').save()
        Movie(key=552, title= '''"Three Musketeers, The''', director='', date=1993, genre='''Action''').save()
        Movie(key=553, title= '''Tombstone''', director='', date=1993, genre='''Action''').save()
        Movie(key=555, title= '''True Romance''', director='', date=1993, genre='''Crime''').save()
        Movie(key=556, title= '''"War Room, The''', director='', date=1993, genre='''Documentary''').save()
        Movie(key=558, title= '''"Pagemaster The''', director='', date=1994, genre='''Action''').save()
        Movie(key=562, title= '''Welcome to the Dollhouse''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=563, title= '''Germinal''', director='', date=1993, genre='''Drama''').save()
        Movie(key=564, title= '''Chasers''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=567, title= '''Kika''', director='', date=1993, genre='''Comedy''').save()
        Movie(key=568, title= '''Bhaji on the Beach''', director='', date=1993, genre='''Comedy''').save()
        Movie(key=569, title= '''Little Big League''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=573, title= '''"Ciao Professore! (Io speriamo che me la cavo)''', director='', date=1992, genre='''Drama''').save()
        Movie(key=574, title= '''Spanking the Monkey''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=575, title= '''"Little Rascals, The''', director='', date=1994, genre='''Children''').save()
        Movie(key=577, title= '''Andre''', director='', date=1994, genre='''Adventure''').save()
        Movie(key=579, title= '''"Escort The (Scorta, La)''', director='', date=1993, genre='''Crime''').save()
        Movie(key=580, title= '''Princess Caraboo''', director='', date=1994, genre='''Drama''').save()
        Movie(key=581, title= '''"Celluloid Closet, The''', director='', date=1995, genre='''Documentary''').save()
        Movie(key=583, title= '''Dear Diary (Caro Diario)''', director='', date=1994, genre='''Comedy''').save()
        Movie(key=585, title= '''"Brady Bunch Movie, The''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=586, title= '''Home Alone''', director='', date=1990, genre='''Children''').save()
        Movie(key=587, title= '''Ghost''', director='', date=1990, genre='''Comedy''').save()
        Movie(key=588, title= '''Aladdin''', director='', date=1992, genre='''Adventure''').save()
        Movie(key=589, title= '''Terminator 2: Judgment Day''', director='', date=1991, genre='''Action''').save()
        Movie(key=590, title= '''Dances with Wolves''', director='', date=1990, genre='''Adventure''').save()
        Movie(key=592, title= '''Batman''', director='', date=1989, genre='''Action''').save()
        Movie(key=593, title= '''"Silence of the Lambs, The''', director='', date=1991, genre='''Crime''').save()
        Movie(key=594, title= '''Snow White and the Seven Dwarfs''', director='', date=1937, genre='''Animation''').save()
        Movie(key=595, title= '''Beauty and the Beast''', director='', date=1991, genre='''Animation''').save()
        Movie(key=596, title= '''Pinocchio''', director='', date=1940, genre='''Animation''').save()
        Movie(key=597, title= '''Pretty Woman''', director='', date=1990, genre='''Comedy''').save()
        Movie(key=599, title= '''"Wild Bunch, The''', director='', date=1969, genre='''Adventure''').save()
        Movie(key=600, title= '''Love and a .45''', director='', date=1994, genre='''Action''').save()
        Movie(key=602, title= '''"Great Day in Harlem, A''', director='', date=1994, genre='''Documentary''').save()
        Movie(key=605, title= '''One Fine Day''', director='', date=1996, genre='''Drama''').save()
        Movie(key=606, title= '''Candyman: Farewell to the Flesh''', director='', date=1995, genre='''Fantasy''').save()
        Movie(key=608, title= '''Fargo''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=609, title= '''Homeward Bound II: Lost in San Francisco''', director='', date=1996, genre='''Adventure''').save()
        Movie(key=610, title= '''Heavy Metal''', director='', date=1981, genre='''Action''').save()
        Movie(key=611, title= '''Hellraiser: Bloodline''', director='', date=1996, genre='''Action''').save()
        Movie(key=612, title= '''"Pallbearer The''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=613, title= '''Jane Eyre''', director='', date=1996, genre='''Drama''').save()
        Movie(key=615, title= '''Bread and Chocolate (Pane e cioccolata)''', director='', date=1973, genre='''Comedy''').save()
        Movie(key=616, title= '''"Aristocats The''', director='', date=1970, genre='''Animation''').save()
        Movie(key=617, title= '''"Flower of My Secret, The (La flor de mi secreto)''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=618, title= '''Two Much''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=619, title= '''Ed''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=626, title= '''"Thin Line Between Love and Hate, A''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=627, title= '''"Last Supper, The''', director='', date=1995, genre='''Drama''').save()
        Movie(key=628, title= '''Primal Fear''', director='', date=1996, genre='''Crime''').save()
        Movie(key=631, title= '''All Dogs Go to Heaven 2''', director='', date=1996, genre='''Adventure''').save()
        Movie(key=632, title= '''Land and Freedom (Tierra y libertad)''', director='', date=1995, genre='''Drama''').save()
        Movie(key=633, title= '''Denise Calls Up''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=634, title= '''Theodore Rex''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=635, title= '''"Family Thing, A''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=636, title= '''Frisk''', director='', date=1995, genre='''Drama''').save()
        Movie(key=637, title= '''Sgt. Bilko''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=638, title= '''Jack and Sarah''', director='', date=1995, genre='''Romance''').save()
        Movie(key=639, title= '''Girl 6''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=640, title= '''Diabolique''', director='', date=1996, genre='''Drama''').save()
        Movie(key=645, title= '''Nelly & Monsieur Arnaud''', director='', date=1995, genre='''Drama''').save()
        Movie(key=647, title= '''Courage Under Fire''', director='', date=1996, genre='''Action''').save()
        Movie(key=648, title= '''Mission: Impossible''', director='', date=1996, genre='''Action''').save()
        Movie(key=649, title= '''Cold Fever (Á köldum klaka)''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=650, title= '''Moll Flanders''', director='', date=1996, genre='''Drama''').save()
        Movie(key=653, title= '''Dragonheart''', director='', date=1996, genre='''Action''').save()
        Movie(key=656, title= '''Eddie''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=661, title= '''James and the Giant Peach''', director='', date=1996, genre='''Adventure''').save()
        Movie(key=662, title= '''Fear''', director='', date=1996, genre='''Thriller''').save()
        Movie(key=663, title= '''Kids in the Hall: Brain Candy''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=665, title= '''Underground''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=667, title= '''Bloodsport 2 (a.k.a. Bloodsport II: The Next Kumite)''', director='', date=1996, genre='''Action''').save()
        Movie(key=668, title= '''Song of the Little Road (Pather Panchali)''', director='', date=1955, genre='''Drama''').save()
        Movie(key=670, title= '''"World of Apu, The (Apur Sansar)''', director='', date=1959, genre='''Drama''').save()
        Movie(key=671, title= '''Mystery Science Theater 3000: The Movie''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=673, title= '''Space Jam''', director='', date=1996, genre='''Adventure''').save()
        Movie(key=674, title= '''Barbarella''', director='', date=1968, genre='''Adventure''').save()
        Movie(key=678, title= '''Some Folks Call It a Sling Blade''', director='', date=1993, genre='''Drama''').save()
        Movie(key=679, title= '''"Run of the Country, The''', director='', date=1995, genre='''Drama''').save()
        Movie(key=680, title= '''"Alphaville (Alphaville, une étrange aventure de Lemmy Caution)''', director='', date=1965, genre='''Drama''').save()
        Movie(key=685, title= '''It's My Party''', director='', date=1996, genre='''Drama''').save()
        Movie(key=688, title= '''Operation Dumbo Drop''', director='', date=1995, genre='''Action''').save()
        Movie(key=691, title= '''Mrs. Winterbourne''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=692, title= '''Solo''', director='', date=1996, genre='''Action''').save()
        Movie(key=694, title= '''"Substitute The''', director='', date=1996, genre='''Action''').save()
        Movie(key=695, title= '''True Crime''', director='', date=1996, genre='''Mystery''').save()
        Movie(key=697, title= '''Feeling Minnesota''', director='', date=1996, genre='''Drama''').save()
        Movie(key=698, title= '''Delta of Venus''', director='', date=1995, genre='''Drama''').save()
        Movie(key=700, title= '''Angus''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=703, title= '''Boys''', director='', date=1996, genre='''Drama''').save()
        Movie(key=704, title= '''"Quest The''', director='', date=1996, genre='''Action''').save()
        Movie(key=706, title= '''Sunset Park''', director='', date=1996, genre='''Drama''').save()
        Movie(key=707, title= '''Mulholland Falls''', director='', date=1996, genre='''Crime''').save()
        Movie(key=708, title= '''"Truth About Cats & Dogs, The''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=709, title= '''Oliver & Company''', director='', date=1988, genre='''Adventure''').save()
        Movie(key=710, title= '''Celtic Pride''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=711, title= '''Flipper''', director='', date=1996, genre='''Adventure''').save()
        Movie(key=714, title= '''Dead Man''', director='', date=1995, genre='''Drama''').save()
        Movie(key=715, title= '''"Horseman on the Roof, The (Hussard sur le toit, Le)''', director='', date=1995, genre='''Drama''').save()
        Movie(key=718, title= '''"Visitors The (Visiteurs, Les)''', director='', date=1993, genre='''Comedy''').save()
        Movie(key=719, title= '''Multiplicity''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=720, title= '''Wallace & Gromit: The Best of Aardman Animation''', director='', date=1996, genre='''Adventure''').save()
        Movie(key=722, title= '''"Haunted World of Edward D. Wood Jr., The''', director='', date=1996, genre='''Documentary''').save()
        Movie(key=724, title= '''"Craft The''', director='', date=1996, genre='''Drama''').save()
        Movie(key=725, title= '''"Great White Hype, The''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=726, title= '''Last Dance''', director='', date=1996, genre='''Drama''').save()
        Movie(key=728, title= '''Cold Comfort Farm''', director='', date=1995, genre='''Comedy''').save()
        Movie(key=731, title= '''Heaven's Prisoners''', director='', date=1996, genre='''Crime''').save()
        Movie(key=733, title= '''"Rock The''', director='', date=1996, genre='''Action''').save()
        Movie(key=735, title= '''Cemetery Man (Dellamorte Dellamore)''', director='', date=1994, genre='''Horror''').save()
        Movie(key=736, title= '''Twister''', director='', date=1996, genre='''Action''').save()
        Movie(key=737, title= '''Barb Wire''', director='', date=1996, genre='''Action''').save()
        Movie(key=741, title= '''Ghost in the Shell (Kôkaku kidôtai)''', director='', date=1995, genre='''Animation''').save()
        Movie(key=742, title= '''Thinner''', director='', date=1996, genre='''Horror''').save()
        Movie(key=743, title= '''Spy Hard''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=745, title= '''Wallace & Gromit: A Close Shave''', director='', date=1995, genre='''Animation''').save()
        Movie(key=747, title= '''"Stupids The''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=748, title= '''"Arrival The''', director='', date=1996, genre='''Action''').save()
        Movie(key=750, title= '''Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb''', director='', date=1964, genre='''Comedy''').save()
        Movie(key=757, title= '''Ashes of Time (Dung che sai duk)''', director='', date=1994, genre='''Drama''').save()
        Movie(key=759, title= '''Maya Lin: A Strong Clear Vision''', director='', date=1994, genre='''Documentary''').save()
        Movie(key=760, title= '''Stalingrad''', director='', date=1993, genre='''Drama''').save()
        Movie(key=761, title= '''"Phantom The''', director='', date=1996, genre='''Action''').save()
        Movie(key=762, title= '''Striptease''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=764, title= '''Heavy''', director='', date=1995, genre='''Drama''').save()
        Movie(key=765, title= '''Jack''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=766, title= '''I Shot Andy Warhol''', director='', date=1996, genre='''Drama''').save()
        Movie(key=773, title= '''Touki Bouki''', director='', date=1973, genre='''Drama''').save()
        Movie(key=775, title= '''Spirits of the Dead''', director='', date=1968, genre='''Horror''').save()
        Movie(key=778, title= '''Trainspotting''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=779, title= ''''Til There Was You''', director='', date=1997, genre='''Drama''').save()
        Movie(key=780, title= '''Independence Day (a.k.a. ID4)''', director='', date=1996, genre='''Action''').save()
        Movie(key=781, title= '''Stealing Beauty''', director='', date=1996, genre='''Drama''').save()
        Movie(key=782, title= '''"Fan The''', director='', date=1996, genre='''Drama''').save()
        Movie(key=783, title= '''"Hunchback of Notre Dame, The''', director='', date=1996, genre='''Animation''').save()
        Movie(key=784, title= '''"Cable Guy, The''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=785, title= '''Kingpin''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=786, title= '''Eraser''', director='', date=1996, genre='''Action''').save()
        Movie(key=788, title= '''"Nutty Professor, The''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=790, title= '''"Unforgettable Summer, An (Un été inoubliable)''', director='', date=1994, genre='''Drama''').save()
        Movie(key=791, title= '''"Last Klezmer: Leopold Kozlowski, His Life and Music, The''', director='', date=1994, genre='''Documentary''').save()
        Movie(key=795, title= '''Somebody to Love''', director='', date=1994, genre='''Drama''').save()
        Movie(key=798, title= '''Daylight''', director='', date=1996, genre='''Action''').save()
        Movie(key=799, title= '''"Frighteners The''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=800, title= '''Lone Star''', director='', date=1996, genre='''Drama''').save()
        Movie(key=801, title= '''Harriet the Spy''', director='', date=1996, genre='''Children''').save()
        Movie(key=802, title= '''Phenomenon''', director='', date=1996, genre='''Drama''').save()
        Movie(key=803, title= '''Walking and Talking''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=804, title= '''She's the One''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=805, title= '''"Time to Kill, A''', director='', date=1996, genre='''Drama''').save()
        Movie(key=806, title= '''American Buffalo''', director='', date=1996, genre='''Crime''').save()
        Movie(key=808, title= '''Alaska''', director='', date=1996, genre='''Adventure''').save()
        Movie(key=809, title= '''Fled''', director='', date=1996, genre='''Action''').save()
        Movie(key=810, title= '''Kazaam''', director='', date=1996, genre='''Children''').save()
        Movie(key=813, title= '''Larger Than Life''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=818, title= '''"Very Brady Sequel, A''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=823, title= '''"Collector The (La collectionneuse)''', director='', date=1967, genre='''Drama''').save()
        Movie(key=824, title= '''Kaspar Hauser''', director='', date=1993, genre='''Drama''').save()
        Movie(key=828, title= '''"Adventures of Pinocchio, The''', director='', date=1996, genre='''Adventure''').save()
        Movie(key=829, title= '''Joe's Apartment''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=830, title= '''"First Wives Club, The''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=832, title= '''Ransom''', director='', date=1996, genre='''Crime''').save()
        Movie(key=833, title= '''High School High''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=835, title= '''Foxfire''', director='', date=1996, genre='''Drama''').save()
        Movie(key=836, title= '''Chain Reaction''', director='', date=1996, genre='''Action''').save()
        Movie(key=837, title= '''Matilda''', director='', date=1996, genre='''Children''').save()
        Movie(key=838, title= '''Emma''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=839, title= '''"Crow: City of Angels, The''', director='', date=1996, genre='''Action''').save()
        Movie(key=840, title= '''House Arrest''', director='', date=1996, genre='''Children''').save()
        Movie(key=841, title= '''"Eyes Without a Face (Yeux sans visage, Les)''', director='', date=1959, genre='''Horror''').save()
        Movie(key=842, title= '''Tales from the Crypt Presents: Bordello of Blood''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=848, title= '''"Spitfire Grill, The''', director='', date=1996, genre='''Drama''').save()
        Movie(key=849, title= '''Escape from L.A.''', director='', date=1996, genre='''Action''').save()
        Movie(key=851, title= '''Basquiat''', director='', date=1996, genre='''Drama''').save()
        Movie(key=852, title= '''Tin Cup''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=858, title= '''"Godfather The''', director='', date=1972, genre='''Crime''').save()
        Movie(key=861, title= '''Supercop (Police Story 3: Supercop) (Jing cha gu shi III: Chao ji jing cha)''', director='', date=1992, genre='''Action''').save()
        Movie(key=866, title= '''Bound''', director='', date=1996, genre='''Crime''').save()
        Movie(key=867, title= '''Carpool''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=869, title= '''Kansas City''', director='', date=1996, genre='''Crime''').save()
        Movie(key=870, title= "Gone Fishin'", director='', date=1997, genre='''Comedy''').save()
        Movie(key=875, title= '''Nothing to Lose''', director='', date=1994, genre='''Action''').save()
        Movie(key=876, title= '''Supercop 2 (Project S) (Chao ji ji hua)''', director='', date=1993, genre='''Action''').save()
        Movie(key=879, title= '''"Relic The''', director='', date=1997, genre='''Horror''').save()
        Movie(key=880, title= '''"Island of Dr. Moreau, The''', director='', date=1996, genre='''Sci-Fi''').save()
        Movie(key=881, title= '''First Kid''', director='', date=1996, genre='''Children''').save()
        Movie(key=882, title= '''"Trigger Effect, The''', director='', date=1996, genre='''Drama''').save()
        Movie(key=885, title= '''Bogus''', director='', date=1996, genre='''Children''').save()
        Movie(key=886, title= '''Bulletproof''', director='', date=1996, genre='''Action''').save()
        Movie(key=888, title= '''Land Before Time III: The Time of the Great Giving''', director='', date=1995, genre='''Adventure''').save()
        Movie(key=889, title= '''1-900 (06)''', director='', date=1994, genre='''Drama''').save()
        Movie(key=891, title= '''Halloween: The Curse of Michael Myers (Halloween 6: The Curse of Michael Myers)''', director='', date=1995, genre='''Horror''').save()
        Movie(key=892, title= '''Twelfth Night''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=893, title= '''Mother Night''', director='', date=1996, genre='''Drama''').save()
        Movie(key=896, title= '''Wild Reeds (Les roseaux sauvages)''', director='', date=1994, genre='''Drama''').save()
        Movie(key=897, title= '''For Whom the Bell Tolls''', director='', date=1943, genre='''Adventure''').save()
        Movie(key=898, title= '''"Philadelphia Story, The''', director='', date=1940, genre='''Comedy''').save()
        Movie(key=899, title= '''Singin' in the Rain''', director='', date=1952, genre='''Comedy''').save()
        Movie(key=900, title= '''"American in Paris, An''', director='', date=1951, genre='''Musical''').save()
        Movie(key=901, title= '''Funny Face''', director='', date=1957, genre='''Comedy''').save()
        Movie(key=902, title= '''Breakfast at Tiffany's''', director='', date=1961, genre='''Drama''').save()
        Movie(key=903, title= '''Vertigo''', director='', date=1958, genre='''Drama''').save()
        Movie(key=904, title= '''Rear Window''', director='', date=1954, genre='''Mystery''').save()
        Movie(key=905, title= '''It Happened One Night''', director='', date=1934, genre='''Comedy''').save()
        Movie(key=906, title= '''Gaslight''', director='', date=1944, genre='''Drama''').save()
        Movie(key=907, title= '''"Gay Divorcee, The''', director='', date=1934, genre='''Comedy''').save()
        Movie(key=908, title= '''North by Northwest''', director='', date=1959, genre='''Action''').save()
        Movie(key=909, title= '''"Apartment The''', director='', date=1960, genre='''Comedy''').save()
        Movie(key=910, title= '''Some Like It Hot''', director='', date=1959, genre='''Comedy''').save()
        Movie(key=911, title= '''Charade''', director='', date=1963, genre='''Comedy''').save()
        Movie(key=912, title= '''Casablanca''', director='', date=1942, genre='''Drama''').save()
        Movie(key=913, title= '''"Maltese Falcon, The''', director='', date=1941, genre='''Film-Noir''').save()
        Movie(key=914, title= '''My Fair Lady''', director='', date=1964, genre='''Comedy''').save()
        Movie(key=915, title= '''Sabrina''', director='', date=1954, genre='''Comedy''').save()
        Movie(key=916, title= '''Roman Holiday''', director='', date=1953, genre='''Comedy''').save()
        Movie(key=917, title= '''"Little Princess, The''', director='', date=1939, genre='''Children''').save()
        Movie(key=918, title= '''Meet Me in St. Louis''', director='', date=1944, genre='''Musical''').save()
        Movie(key=919, title= '''"Wizard of Oz, The''', director='', date=1939, genre='''Adventure''').save()
        Movie(key=920, title= '''Gone with the Wind''', director='', date=1939, genre='''Drama''').save()
        Movie(key=921, title= '''My Favorite Year''', director='', date=1982, genre='''Comedy''').save()
        Movie(key=922, title= '''Sunset Blvd. (a.k.a. Sunset Boulevard)''', director='', date=1950, genre='''Drama''').save()
        Movie(key=923, title= '''Citizen Kane''', director='', date=1941, genre='''Drama''').save()
        Movie(key=924, title= '''2001: A Space Odyssey''', director='', date=1968, genre='''Adventure''').save()
        Movie(key=926, title= '''All About Eve''', director='', date=1950, genre='''Drama''').save()
        Movie(key=927, title= '''"Women The''', director='', date=1939, genre='''Comedy''').save()
        Movie(key=928, title= '''Rebecca''', director='', date=1940, genre='''Drama''').save()
        Movie(key=929, title= '''Foreign Correspondent''', director='', date=1940, genre='''Drama''').save()
        Movie(key=930, title= '''Notorious''', director='', date=1946, genre='''Film-Noir''').save()
        Movie(key=931, title= '''Spellbound''', director='', date=1945, genre='''Mystery''').save()
        Movie(key=932, title= '''"Affair to Remember, An''', director='', date=1957, genre='''Drama''').save()
        Movie(key=933, title= '''To Catch a Thief''', director='', date=1955, genre='''Crime''').save()
        Movie(key=934, title= '''Father of the Bride''', director='', date=1950, genre='''Comedy''').save()
        Movie(key=935, title= '''"Band Wagon, The''', director='', date=1953, genre='''Comedy''').save()
        Movie(key=936, title= '''Ninotchka''', director='', date=1939, genre='''Comedy''').save()
        Movie(key=937, title= '''Love in the Afternoon''', director='', date=1957, genre='''Comedy''').save()
        Movie(key=938, title= '''Gigi''', director='', date=1958, genre='''Musical''').save()
        Movie(key=940, title= '''"Adventures of Robin Hood, The''', director='', date=1938, genre='''Action''').save()
        Movie(key=941, title= '''"Mark of Zorro, The''', director='', date=1940, genre='''Adventure''').save()
        Movie(key=942, title= '''Laura''', director='', date=1944, genre='''Crime''').save()
        Movie(key=943, title= '''"Ghost and Mrs. Muir, The''', director='', date=1947, genre='''Drama''').save()
        Movie(key=944, title= '''Lost Horizon''', director='', date=1937, genre='''Drama''').save()
        Movie(key=945, title= '''Top Hat''', director='', date=1935, genre='''Comedy''').save()
        Movie(key=946, title= '''To Be or Not to Be''', director='', date=1942, genre='''Comedy''').save()
        Movie(key=947, title= '''My Man Godfrey''', director='', date=1936, genre='''Comedy''').save()
        Movie(key=948, title= '''Giant''', director='', date=1956, genre='''Drama''').save()
        Movie(key=949, title= '''East of Eden''', director='', date=1955, genre='''Drama''').save()
        Movie(key=950, title= '''"Thin Man, The''', director='', date=1934, genre='''Comedy''').save()
        Movie(key=951, title= '''His Girl Friday''', director='', date=1940, genre='''Comedy''').save()
        Movie(key=952, title= '''Around the World in 80 Days''', director='', date=1956, genre='''Adventure''').save()
        Movie(key=953, title= '''It's a Wonderful Life''', director='', date=1946, genre='''Children''').save()
        Movie(key=954, title= '''Mr. Smith Goes to Washington''', director='', date=1939, genre='''Drama''').save()
        Movie(key=955, title= '''Bringing Up Baby''', director='', date=1938, genre='''Comedy''').save()
        Movie(key=956, title= '''Penny Serenade''', director='', date=1941, genre='''Drama''').save()
        Movie(key=959, title= '''Of Human Bondage''', director='', date=1934, genre='''Drama''').save()
        Movie(key=961, title= '''Little Lord Fauntleroy''', director='', date=1936, genre='''Drama''').save()
        Movie(key=963, title= '''"Inspector General, The''', director='', date=1949, genre='''Musical''').save()
        Movie(key=965, title= '''"39 Steps, The''', director='', date=1935, genre='''Drama''').save()
        Movie(key=968, title= '''Night of the Living Dead''', director='', date=1968, genre='''Horror''').save()
        Movie(key=969, title= '''"African Queen, The''', director='', date=1951, genre='''Adventure''').save()
        Movie(key=970, title= '''Beat the Devil''', director='', date=1953, genre='''Adventure''').save()
        Movie(key=971, title= '''Cat on a Hot Tin Roof''', director='', date=1958, genre='''Drama''').save()
        Movie(key=973, title= '''Meet John Doe''', director='', date=1941, genre='''Comedy''').save()
        Movie(key=976, title= '''"Farewell to Arms, A''', director='', date=1932, genre='''Romance''').save()
        Movie(key=979, title= '''Nothing Personal''', director='', date=1995, genre='''Drama''').save()
        Movie(key=981, title= '''Dangerous Ground''', director='', date=1997, genre='''Drama''').save()
        Movie(key=982, title= '''Picnic''', director='', date=1955, genre='''Drama''').save()
        Movie(key=984, title= '''"Pompatus of Love, The''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=986, title= '''Fly Away Home''', director='', date=1996, genre='''Adventure''').save()
        Movie(key=987, title= '''Bliss''', director='', date=1997, genre='''Drama''').save()
        Movie(key=988, title= '''Grace of My Heart''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=990, title= '''Maximum Risk''', director='', date=1996, genre='''Action''').save()
        Movie(key=991, title= '''Michael Collins''', director='', date=1996, genre='''Drama''').save()
        Movie(key=993, title= '''Infinity''', director='', date=1996, genre='''Drama''').save()
        Movie(key=994, title= '''Big Night''', director='', date=1996, genre='''Comedy''').save()
        Movie(key=996, title= '''Last Man Standing''', director='', date=1996, genre='''Action''').save()
        Movie(key=998, title= '''Set It Off''', director='', date=1996, genre='''Action''').save()
        Movie(key=999, title= '''2 Days in the Valley''', director='', date=1996, genre='''Crime''').save()
        Movie(key=1003, title= '''Extreme Measures''', director='', date=1996, genre='''Drama''').save()

            

    @staticmethod
    def get_all():

        return Movie.query.all()

    def get_by_title(title):
        return Movie.query.filter_by(title=title)

    def get_by_genre(genre):
        return Movie.query.filter_by(genre=genre)

    def getbykey(key):

        return Movie.query.filter_by(key=key).one()

    def update(self, key, title, director, date, genre):

        movie = self.get(title, director)
        movie.date = date
        movie.director= director
        movie.key=key
        movie.genre=genre

        return movie.save()

    @staticmethod
    def create(key, title, director, date, genre):

        movie = Movie(key=key, title=title, director=director, date=date, genre=genre)
        return movie.save()

