"""empty message

Revision ID: 0138f3a43814
Revises: None
Create Date: 2019-06-19 10:12:26.439959

"""

# revision identifiers, used by Alembic.
revision = '0138f3a43814'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('key', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('director', sa.String(length=300), nullable=True),
    sa.Column('date', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('rate',
    sa.Column('user_rating', sa.Integer(), nullable=False),
    sa.Column('movie_rated', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_rating', 'movie_rated')
    )
    op.create_table('user',
    sa.Column('key', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=300), nullable=True),
    sa.Column('last_name', sa.String(length=300), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('rate')
    op.drop_table('movie')
    # ### end Alembic commands ###
