"""empty message

Revision ID: 418958e9c9db
Revises: a38bd89c1020
Create Date: 2019-06-18 11:20:08.110180

"""

# revision identifiers, used by Alembic.
revision = '418958e9c9db'
down_revision = 'a38bd89c1020'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
