"""empty message

Revision ID: 57355d0c2a86
Revises: 0138f3a43814
Create Date: 2019-06-19 11:51:20.039659

"""

# revision identifiers, used by Alembic.
revision = '57355d0c2a86'
down_revision = '0138f3a43814'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('genre', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'genre')
    # ### end Alembic commands ###
