"""empty message

Revision ID: 74239c5d2cd8
Revises: 418958e9c9db
Create Date: 2019-06-18 11:40:02.574600

"""

# revision identifiers, used by Alembic.
revision = '74239c5d2cd8'
down_revision = '418958e9c9db'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
