"""empty message

Revision ID: 78456522dc06
Revises: b6d86eb246a9
Create Date: 2019-06-18 14:19:22.749770

"""

# revision identifiers, used by Alembic.
revision = '78456522dc06'
down_revision = 'b6d86eb246a9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
