"""empty message

Revision ID: a38bd89c1020
Revises: 517a6c42fc5d
Create Date: 2019-06-18 11:15:58.594167

"""

# revision identifiers, used by Alembic.
revision = 'a38bd89c1020'
down_revision = '517a6c42fc5d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
