"""empty message

Revision ID: b6d86eb246a9
Revises: 74239c5d2cd8
Create Date: 2019-06-18 11:45:58.689243

"""

# revision identifiers, used by Alembic.
revision = 'b6d86eb246a9'
down_revision = '74239c5d2cd8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
