"""empty message

Revision ID: da581bff6d8d
Revises: 78456522dc06
Create Date: 2019-06-18 15:00:58.530572

"""

# revision identifiers, used by Alembic.
revision = 'da581bff6d8d'
down_revision = '78456522dc06'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate',
    sa.Column('user_rating', sa.Integer(), nullable=False),
    sa.Column('movie_rated', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_rating', 'movie_rated')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rate')
    # ### end Alembic commands ###
